### ISSUE TITLE
Does This Work with Android 31

### ISSUE THREAD

**Issue by primitivetypo** [LerryAlexander/docker-android-selenium-grid#1]
Hi, 

I tried this and I hit several errors with emulator starting up but no tests run, just stuck in the in the start state. Also can this be used with latest android version 31?

Thanks

**Comment by primitivetypo** [comment]
Could you please share your email to discuss some questions?

**Comment by LerryAlexander** [comment]
Hi @primitivetypo,

Which machine are you using for running this? This repo should be able to run with any of the emulators provided here: https://github.com/budtmo/docker-android#list-of-docker-images

email: lerry.ortiz@gmail.com
